# These are supported funding model platforms
# Uncomment and fill in the platforms you use

github: [michael_marvive]
# patreon: # Replace with your Patreon username
# ko_fi: # Replace with your Ko-fi username
# buy_me_a_coffee: # Replace with your Buy Me a Coffee username
# custom: ["https://your-custom-link.com"]
